### PR TITLE
feat: add `frameMax` connection option

### PR DESCRIPTION
**Pull request by dwickr**
Add the `frameMax` connection tuning parameter as implemented in amqplib[1]. Default to 4k (4096) to match amqplib's default.

[1]: https://amqp-node.github.io/amqplib/channel_api.html#tuning-parameters

### CODE REVIEW

**Comment by dwickr** [comment]
hey @zlintz would you mind reviewing this one? thank you!

**Review by zlintz — CHANGES_REQUESTED** [review]
I think the implementation is correct, the only change I would suggest is making it optional to be consistent with past behavior rather than a default from our side.  

Consulting the great GPT oracle with a grain of salt of course, indicated 
>The default size for frameMax in RabbitMQ is 131072 bytes, which is equivalent to 128 KB.

vs the 4096 bytes being proposed as the default

**Comment by dwickr** [comment]
@zlintz thanks for the feedback. I can look into changing this to be optional instead. The current default of this value set by amqplib -- and therefore this package -- is 4096 bytes. I can increase it to the RabbitMQ default of 128KiB, but that would be a slight change in behavior here.

**Comment by zlintz** [comment]
Ah I see what you mean https://github.com/amqp-node/amqplib/blob/64d1c1ec19afa64a7ec5c355ea7620f0b227fb30/lib/connect.js#L69

In this case, I don't think you need to adjust your proposal. I will try and get this merged in and released. 

Thank you for contributing

**Review by zlintz — APPROVED** [review]

**Pull request merged**
