### PR TITLE
feat(.nvmrc, package.json, info.js, test-coverage-actions.yml): add s…

### LINKED ISSUE #37: Support for node 18?
Greetings,

The package.json ([line 8)](https://github.com/Foo-Foo-MQ/foo-foo-mq/blob/f07b86f21c71e31dd47987b2b514151ab6631cd5/package.json#L8) stipulate it only support node 12 up to and including 16.
Considering v18 is about to reach Active LTS in a few months, I wonder if this could be changed. The issue now is that it is breaking my docker build due to the incompatible engines (`node:18-alpine`).

### PR DESCRIPTION
**Pull request by forrest-labrum**
…upport for node 18

Adds support for node 18, as it is now LTS. Modifies the hash for unique queue names to use md5 instead of md4, md4 was broken by node 17's upgrade to OpenSSL3.

fix #37

### CODE REVIEW

**Comment by zlintz** [comment]
Oh snap @forrest-labrum !

Thank you for this. I will try to take a look at this sooner than later. The GitHub pipeline I am sure is currently broken (still attempting to move over to it ever since TravisCI stopped being free for open source) but if this runs locally I'll get this in.

**Comment by forrest-labrum** [comment]
@zlintz no worries, hope you're doing well!

**Comment by zlintz** [comment]
Hey just checking back on this, in trying to run on node 18 even with this change I am still seeing failed tests. I'm not saying the tests are wrong but they were still working on 16. I think there is something more going on here

**Comment by zlintz** [comment]
@forrest-labrum hey not sure what change with node or maybe I was just having an issue for a minute with the version of 18 I was using but I just did a release because things are working and passing tests.  Look for version 8.0.0

Thanks again!

**Comment by forrest-labrum** [comment]
@zlintz Ah dang, you had reviewed right before I left for the holidays and I totally forgot about this. Thanks for circling back on it and getting it merged in!

**Comment by zlintz** [comment]
No problem, I am not sure exactly what was going on, maybe just a local dev env problem, but after I came back to I had no problems.  Could have been a bug in an early node 18 version as far as I know because the only thing I can think of I did was get a current copy of 18 (i.e. `nvm install`) and it was happy

**Pull request merged**
