### PR TITLE
feat: typescript support

### PR DESCRIPTION
**Pull request by grimurd**
I wrote these typescript types several years ago and have been using them without any problems thus far.

They were written mostly using the publicly documented api with some additions made after going through the code where documentation was missing.

### CODE REVIEW

**Comment by ACA-Alexandre** [comment]
I am also interested by a TypeScript support 🙂

**Review by geoffreyLB — APPROVED** [review]

**Review by amacabr2 — APPROVED** [review]

**Comment by zlintz** [comment]
Thanks for providing this.  It is definitely something @auroq and I have been talking about doing as well

@auroq This seems reasonable to me, any thoughts

**Comment by MartianH** [comment]
Is there any progress on this? @grimurd @zlintz @auroq

**Comment by zlintz** [comment]
This is merged to master and will go out with the next release.  It is possible the names of the types may change if/when the codebase moves to typescript

**Pull request merged**
